### ISSUE TITLE
RCSR database file is not complete

### ISSUE THREAD

**Issue by gooaah** [odf/gavrog#10]
I'm trying to build structures from RCSR nets to explore novel phases. I use the .arc and .cgd files from http://rcsr.anu.edu.au/systre. But I find the nets in the files are less than those shown on the website. Where can I find all RCSR nets?

**Comment by odf** [comment]
The .arc and .cgd files on RCSR as well as the latest Systre release have now been updated to reflect the contents of the RCSR database as of 1 June, 2019. Note however that certain types of nets can not be represented adequately by Systre (e.g. -b, -c, -z and -w nets as well as non-crystallographic nets) and are thus not included in the files.
