### ISSUE TITLE
How to generate unique keys for nets from the command line

### ISSUE THREAD

**Issue by paulneves77** [odf/gavrog#12]
Hi, I am working on a project that needs to call Systre on tens of thousands of crystal nets (which, incidentally, is great at finding bugs). It would be great if I could call Systre on each net automatically via command line, and automatically save the output. I see the previous issue where you detailed how to run Systre from the command line, but I see no documentation on how to save the result from the calculation in the same call.

**Comment by odf** [comment]
Both the original (Java) command line version and the Jython script write to the standard output. All you should need to do in order to get it written into a file is append a redirection of the form `>filename` to the command.

**Comment by paulneves77** [comment]
Thanks for the response. Unfortunately, this does not solve my problem. I need the "key" as is saved in the .arc files the GUI produces so that I can classify these graphs. While the command line output lists much useful information, it does not include the critical "key" that I need. Is there any way to add this key to the output/generate the .arc file/etc? Thanks!

**Comment by odf** [comment]
Ah, I see. Both version support the `-a archivename` option to specify an output archive file.  Only structures that are "new for this run" are written out to the archive, so you might want to tell the script to skip reading the builtin Systre archive (`-n` in Jython, `--noBuiltin` in Java).

Alternatively, you could tell Systre to include the key as part of the normal output (`-k` in Jython, `--systreKey` in Java).

If you use the Jython script, you can get a list of available options by calling it with `-h`.

I hope that helps.

**Comment by paulneves77** [comment]
Perfect, thank you. This solves my problem!
