### ISSUE TITLE
2D Structures in Web Gavrog Broken

### ISSUE THREAD

**Issue by paulneves77** [odf/gavrog#15]
Hi again. I seem to be having a problem with web Gavrog (http://gavrog.org/webGavrog/) when trying to display some 2D structures. All it tells me when I try to open the .cgd file is "ERROR processing structure 1!!!."

An example input that produces this error is:

PERIODIC_GRAPH
ID Kagome
EDGES
  2 0 0 1 0
  0 1 0 0 0
  1 0 0 1 0
  0 2 1 0 0
  1 2 0 0 0
  1 2 1 0 0
END

**Comment by odf** [comment]
Because of the extra `0` at the end of each edge specification, webGavrog thinks this is a 3d net and tries to process it accordingly.  With those removed, it works.

**Comment by paulneves77** [comment]
Ok, thanks for the tip! I had this problem with several 2D graphs with 3D coordinates and this has resolved all of them.
