### ISSUE TITLE
3dt: Screenshots use too much memory

### ISSUE THREAD

**Issue by psavery** [odf/gavrog#8]
When I try to take a screenshot with 3dt (via the File -> Screen Shot... menu), I always get this error:

    java.lang.OutOfMemoryError: Java heap space

And then, when I take subsequent screenshots, it results in just a black image with nothing in it.

I have tried this for both .png and .jpg extensions.

I am using Windows 10 and the 0.6.0 beta2.

**Comment by odf** [comment]
Sorry for the late reply! If you are still interested in a solution, look at the file `3dt.bat` that was created by the installation script. It contains the command line option `-Xmx512m` or something similar near the end, in the java command. Depending on your computer and Java version, you can probably increase the number from 512 megabytes to something much larger, or even remove this option completely.
