### ISSUE TITLE
3dt: add/remove tile shortcuts do not work

### ISSUE THREAD

**Issue by psavery** [odf/gavrog#9]
If I right-click on a tile, I see from the context menu that the "A" key should add a tile, the "D" key should remove a tile, and the  "Shift-D" key should remove a tile class.

However, when I try these shortcuts, tiles do not get added or removed. Instead, the view changes. I guess this is because when I click on the "View" menu option at the top, I see there are also view shortcuts for the "A" and "D" keys. I guess there are conflicting shortcut keys.

I am using Windows 10 and the 0.6.0 beta2.

**Comment by odf** [comment]
That's probably what it is, but since none of my computers can run 3dt anymore, I will not be able to fix the problem. There is a replacement for 3dt in the works, to be found at http://gavrog.org/webGavrog/.
